version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@blogtemplate.51z0m.mongodb.net/blog?retryWrites=true&w=majority
      - JWT_SECRET=${JWT_SECRET:-defaultsecret}
      - PORT=8080
    restart: always

networks:
  default:
    driver: bridge
