version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/blog
      - JWT_SECRET=sua_chave_secreta_aqui
      - PORT=8080
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: always

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: always
    command: mongod --bind_ip_all
    environment:
      - MONGODB_DATABASE=blog

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
