version: '3.8'

services:
  app:
    image: seu_usuario/blog-app:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/blog
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    restart: always
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    command: mongod --bind_ip_all
    environment:
      - MONGODB_DATABASE=blog
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local