version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MONGODB_URI=${MONGODB_URI}
        - JWT_SECRET=${JWT_SECRET}
        - PORT=${PORT}
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080
      - NODE_ENV=production
    restart: always

networks:
  default:
    driver: bridge
